pipeline {

    agent any

    environment {

        IMAGE_NAME = "saichandu27/sample-app"
        IMAGE_TAG  = "v1.0"

    }

    stages {

        stage('Pull Docker Image') {

            steps {

                sh '''
                docker pull ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Trivy Vulnerability Scan') {

            steps {

                sh '''
                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Deploy Container') {

            steps {

                sh '''
                docker rm -f flask-app || true

                docker run -d \
                --name flask-app \
                -p 5000:5000 \
                ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Verify Deployment') {

            steps {

                sh 'docker ps'

                sh 'curl -I http://localhost:5000'
            }
        }
    }

    post {

        success {

            echo 'Application Deployed Successfully'
        }

        failure {

            echo 'Pipeline Failed'
        }
    }
}
